Repository arpastrana/apc524_directional_clustering, pull requests merged in 2020-12, with the labels that each got.

#26 Completed docstrings and testing suite for directional_clustering.clustering
  requirements.txt
  src/directional_clustering/clustering/clustering_factory.py
  src/directional_clustering/clustering/kmeans/_kmeans.py
  src/directional_clustering/clustering/kmeans/cosine.py
  src/directional_clustering/clustering/kmeans/operations.py
  src/directional_clustering/clustering/kmeans/variational.py
  tests/clustering/kmeans/conftest.py
  tests/clustering/kmeans/test_cosine.py
  tests/clustering/kmeans/test_kmeans.py
  tests/clustering/kmeans/test_operations.py
  tests/clustering/kmeans/test_variational.py
  tests/clustering/test_factory.py
  tests/fields/test_field.py
  tests/fields/test_vector_field.py
  tests/transformations/test_smooth.py
Labels: documentation, enhancement

#29 Plotters
  scripts/01_directional_clustering.py
  scripts/02_plot_vectors.py
  src/directional_clustering/plotters/__init__.py
  src/directional_clustering/plotters/cluster_plotter.py
  src/directional_clustering/plotters/plot_data_struct.py
  src/directional_clustering/plotters/ply_plotter.py
  tests/plotters/conftest.py
  tests/plotters/test_lines.py
  tests/plotters/test_plot_data_struct.py
Labels: enhancement

#41 Requirements
  requirements-dev.txt
  requirements.txt
  scripts/01_plotting.py
  src/directional_clustering/plotters/__init__.py
  src/directional_clustering/plotters/ply_plotter.py
Labels: bug, documentation
